/*
 * DocumentInfoFrame.java
 *
 * Created on July 29, 2007, 11:37 AM
 */

package org.topon.client.gui;

import java.util.Date;
import org.topon.database.DocumentModel;

/**
 *
 * @author  topon
 */
public class DocumentInfoFrame extends javax.swing.JDialog {
    DocumentModel docMod;
    /** Creates new form DocumentInfoFrame */
    public DocumentInfoFrame(DocumentModel docMod) {
        this.setModal(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.docMod = docMod;
        initComponents();
        setComponentsTexts();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        docURLjTextField1 = new javax.swing.JTextField();
        validStartjTextField2 = new javax.swing.JTextField();
        validEndjTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionjTextArea1 = new javax.swing.JTextArea();
        titleJLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        closejButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("documenturl");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(11, 15, 11, 15);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("valid start");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 16, 12, 16);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("valid end");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(jLabel3, gridBagConstraints);

        docURLjTextField1.setEditable(false);
        docURLjTextField1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        jPanel2.add(docURLjTextField1, gridBagConstraints);

        validStartjTextField2.setEditable(false);
        validStartjTextField2.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 17, 10, 17);
        jPanel2.add(validStartjTextField2, gridBagConstraints);

        validEndjTextField3.setEditable(false);
        validEndjTextField3.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 17, 10, 17);
        jPanel2.add(validEndjTextField3, gridBagConstraints);

        jLabel4.setText("description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Metadata");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel5, gridBagConstraints);

        descriptionjTextArea1.setColumns(20);
        descriptionjTextArea1.setEditable(false);
        descriptionjTextArea1.setRows(5);
        jScrollPane1.setViewportView(descriptionjTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 154;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 24, 10, 27);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        titleJLabel.setText("Detailed informations about Document");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 400;
        jPanel2.add(titleJLabel, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        closejButton1.setText("close");
        closejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closejButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 11, 18);
        jPanel3.add(closejButton1, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closejButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_closejButton1ActionPerformed
    
    private void setComponentsTexts() {
        docURLjTextField1.setText(docMod.getDocURL());
        validStartjTextField2.setText(new Date(docMod.getValidStart()).toString());
        validEndjTextField3.setText(new Date(docMod.getValidEnd()).toString());
        descriptionjTextArea1.setText(docMod.getDescription());
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closejButton1;
    private javax.swing.JTextArea descriptionjTextArea1;
    private javax.swing.JTextField docURLjTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JTextField validEndjTextField3;
    private javax.swing.JTextField validStartjTextField2;
    // End of variables declaration//GEN-END:variables
    
}
